# Generated by Django 4.2.30 on 2026-04-12 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_action_0c0ad1_idx',
            old_name='audit_action_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_user_id_39eebe_idx',
            old_name='audit_user_created_idx',
        ),
    ]
