# Generated by Django 4.2.30 on 2026-04-12 01:22

import autoaid.apps.diagnostics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedmedia',
            name='file',
            field=models.FileField(upload_to=autoaid.apps.diagnostics.models.issue_upload_path),
        ),
    ]
